### ISSUE TITLE
Not an issue but may come in handy - D.U.C. setup for reverse Proxy DynDNS for NIGNX setup under Ubuntu with Nextcloud

### ISSUE THREAD

**Issue by carling-knock** [jameskimmel/Nextcloud_Ubuntu#3]
Take this as a little contribution to the whole project ;-)

There is one Optional section that may be coming in handy for some private user like me, who want to setup a Nextcloud Server, want to make use of this extensive Installation script, but have not yet got their own domain and DynDNS with DUC in place!!!

Well, to activate any sort of DUC for DynDNS setup is something that at best is done before starting to follow the main manual, so this part is a additional “sample” on how to make it seamlessly work for:
[Example installation on Ubuntu 22.04.03 LTS with Apache2, APCu, redis and mariadb behind a NGINX proxy, no Docker, no Snap](https://github.com/jameskimmel/Nextcloud_Ubuntu/blob/main/nextcloud.md#example-installation-on-ubuntu-220403-lts-with-apache2-apcu-redis-and-mariadb-behind-a-nginx-proxy-no-docker-no-snap)

Explaining the whole procedure on how to get an "own_Domane" setup may be reaching beyond this manual, but once the Installation of "reverts Proxy with NIGX" is in place, this additional quirk adding to it.
And yes this will work as well if shipping the NGINX section, but causing trouble as I learned the hard way, but will do as a sample ;-)
(I'm not associated with No-IP service provider, but choosing it for my own purposes because my Router is capable to hook in with it, as well as making use of it and is easy to put in place too ;-)

Free Dynamic DNS from No-IP provider: https://www.noip.com/
an account is needed for setting up a new domain and all this is needed prior to add a certbot certificate to be successful, you need an A or AAAA configured already to be able to complet this step:
 [NGINX settings on the reverse Proxy](https://github.com/jameskimmel/Nextcloud_Ubuntu/blob/main/nextcloud.md#nginx-settings-on-the-reverse-proxy)
#No-IP Linux DUC Dynamic Update Client on Ubuntu
#You will be able to install No-IP.com’s DUC on Ubuntu in just a few minutes with Terminal.

#install No-IP DUC

cd /usr/local/src/
wget http://www.noip.com/client/linux/noip-duc-linux.tar.gz
tar xf noip-duc-linux.tar.gz
cd noip-2.1.9-1/
apt install gcc
apt install make
make install

#You will then be prompted to log in with your No-IP account username and password.

#if you get “make not found” or “missing gcc” then you do not have the gcc compiler tools on your machine.
#You will need to install these in order to proceed.

#To Configure the Client
sudo /usr/local/bin/noip2 -C

#You will then be prompted for your No-IP username and password, as well as the hostnames you wish to update.
#Be careful, one of the questions is “Do you wish to update ALL hosts.”
#If answered incorrectly, this could affect hostnames in your account that are pointing at other locations.

#final command to launch the client in the background:
sudo /usr/local/bin/noip2

#Read the README file in the no-ip-2.1.9 folder for instructions on how to make the client run at startup.
#This varies depending on what Linux distribution you are running.
#Typically, to run the client at startup you will use:

sudo nano /usr/local/etc/no-1p2.conf

$ systemctl enable noip2.service (start on boot)
$ systemctl start noip2.service (start immediately)
$ systemctl status noip2.service (for status)

The DUC should now be installed on Ubuntu.

**In case this no-ip2 client does not restart automatically at boot or startup, it may, would be nice to get it restarted with a CRON job if possible, so far I haven't figured it out.**

**Comment by jameskimmel** [comment]
Added it to the wiki
